### ISSUE TITLE
installation command is not working

### ISSUE THREAD

**Issue by bue-twitter** [xeroc/stakemachine#7]
following installation command is not working 

`python3 setup.py install --user -r requirements.txt`

**error: option -r not recognized**

https://steemit.com/bitshares/@xeroc/stakemachine-trading-infrastructure-and-simple-market-making-bot-for-bitshares--opensource-bot-for-bitshares

**Comment by xeroc** [comment]
woops .. should have been

```
pip3 install -r requirements.txt --user
```
